src/Ueb/UebOfThingsBundle/Entity/Notification.php
<?php



/**
 * Description of Notification
 *
 * @author joao
 */

namespace Ueb\UebOfThingsBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * FeedData
 *
 * @ORM\Table(name="notification")
 * @ORM\Entity(repositoryClass="Ueb\UebOfThingsBundle\Repository\NotificationRepository")
 */
class Notification {
    
    const WARNING = 0;
    const CRITICAL = 1;
    
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    /**
     *
     * @var type
     * 
     * @ORM\OneToOne(targetEntity="FeedData") 
     * @ORM\JoinColumn(name="feeddata_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $feeddata;
    
    
    /**
     *
     * @ORM\Column(name="type", type="integer")
     */
    private $type;
    
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set feeddata
     *
     * @param \Ueb\UebOfThingsBundle\Entity\FeedData $feeddata
     * @return Notification
     */
    public function setFeeddata(\Ueb\UebOfThingsBundle\Entity\FeedData $feeddata = null)
    {
        $this->feeddata = $feeddata;

        return $this;
    }

    /**
     * Get feeddata
     *
     * @return \Ueb\UebOfThingsBundle\Entity\FeedData 
     */
    public function getFeeddata()
    {
        return $this->feeddata;
    }

    
    

    /**
     * Set type
     *
     * @param integer $type
     * @return Notification
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return integer 
     */
    public function getType()
    {
        return $this->type;
    }
    
    public function getTypeToString() {
        switch ($this->type) {
            case self::WARNING:
                    return "warning";
            case self::CRITICAL:
                    return "critical";
            default: 
                return null;
        }
    }
}

src/Ueb/UebOfThingsBundle/Controller/DefaultController.php
<?php

namespace Ueb\UebOfThingsBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\SecurityContext;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Ueb\UebOfThingsBundle\Form\UserType;

/**
 * 
 * @Route("/")
 */
class DefaultController extends Controller
{
    
    public function indexAction()
    {
        //Esta secção poderia ser mais eficiente com uma query a BD mas para ja assim ficará
        $em = $this->getDoctrine()->getManager();
        $repository= $em->getRepository("UebUebOfThingsBundle:Feed");
        $feeds = $repository->findAll();
        $stats = $this->feedStats($repository, $feeds);
        // 
        
        $breadcrumbs = $this->get("white_october_breadcrumbs");
        $breadcrumbs->addItem("Dashboard");
        return $this->render('UebUebOfThingsBundle:Default:index.html.twig', 
                array(
                    'normal' => $stats['normal'],
                    'warning' => $stats['warning'],
                    'critical' => $stats['critical']
                )
        );
    }
    
    
    /**
     * 
     * @Route("login", name="login")
     */
    public function loginAction(){
        $request = $this->getRequest();
        $session = $request->getSession();
 
        // get the login error if there is one
        if ($request->attributes->has(SecurityContext::AUTHENTICATION_ERROR)) {
            $error = $request->attributes->get(SecurityContext::AUTHENTICATION_ERROR);
        } else {
            $error = $session->get(SecurityContext::AUTHENTICATION_ERROR);
            $session->remove(SecurityContext::AUTHENTICATION_ERROR);
        }
        
        $breadcrumbs = $this->get("white_october_breadcrumbs");
        $breadcrumbs->addItem("Dashboard", $this->generateUrl('homepage'));
        $breadcrumbs->addItem("Login");
 
        return $this->render('UebUebOfThingsBundle:Default:login.html.twig', array(
            // last username entered by the user
            'last_username' => $session->get(SecurityContext::LAST_USERNAME),
            'error'         => $error,
        ));
    }
    
    /**
     * @Route("login_check", name="login_check")
     */
    public function loginCheckAction()
    {

    }
    
    /**
     * @Route("logout", name="logout")
     */
    public function logoutAction(){
        
    }
    
    
    /**
     * 
     * @Route("clean_notifications", name="clean_notifications")
     * @Method("POST")
     */
    public function cleanNotificationsAction() {
        
        $em = $this->getDoctrine()->getManager();
        
        $user = $this->getUser();
        $user->removeNotifications();
        
        $em->persist($user);
        $em->flush();
        
        return new Response("ok", Response::HTTP_OK);
        
    }
    
    
    /**
     * 
     * @Route("settings", name="user_settings")
     * @Method("GET")
     * @Template()
     */
    public function settingsAction() {
        
        $user = $this->getUser();
        
        $settingsForm = $this->createForm(new UserType(), $user, array(
            'action' => $this->generateUrl('user_settings_update'),
            'method' => 'PUT',
        ));
        
        $breadcrumbs = $this->get("white_october_breadcrumbs");
        $breadcrumbs->addItem("Dashboard", $this->generateUrl('homepage'));
        $breadcrumbs->addItem("Definições");
        
        return array(
            'form' => $settingsForm->createView()
        );
        
    }
    
    /**
     *
     *
     * @Route("settings", name="user_settings_update")
     * @Method("PUT")
     * @Template("UebUebOfThingsBundle:Board:edit.html.twig")
     */
    public function settingsUpdateAction(Request $request) {
        
        $em = $this->getDoctrine()->getManager();
        
        $user = $this->getUser();
        
        $settingsForm = $this->createForm(new UserType(), $user, array(
            'action' => $this->generateUrl('user_settings_update'),
            'method' => 'PUT',
        ));

        $settingsForm->handleRequest($request);

        if ($settingsForm->isValid()) {
            $em->flush();

            return $this->redirect($this->generateUrl('user_settings'));
        }

        return array(
            'form'      => $settingsForm->createView()
        );
    }
    
    
    /*
     * aux function
     * return array
     * 
     * returns an indexed array["normal"=>x, "warning"=>y , "critical"=>z]
     */
    private function feedStats($repository, $feed_array) {
        
        $normal = 0;
        $warning = 0;
        $critical = 0;


        foreach ($feed_array as $f) {
            $feed = $repository->findFeedJoinedByFeedData($f->getId(), 'hour');
            if ($feed != null) {
                $normal+= $feed->getCountNormalValues();
                $warning+= $feed->getCountWarningValues();
                $critical+= $feed->getCountCriticalValues();
            }
        }

        return array(
            'normal' => $normal,
            'warning' => $warning,
            'critical' => $critical
        );
    }

}

src/Ueb/UebOfThingsBundle/Resources/views/Default/index.html.twig
{% extends 'UebUebOfThingsBundle::layout.html.twig' %}

{% block javascripts %}
    {{ parent () }}
{% endblock %}

{% block content -%}
    
    <h1>Dashboard <small>Vista Geral</small></h1>
    {{ wo_render_breadcrumbs() }}
    <!-- /.row -->

    <div class="row">
        <div class="col-lg-3">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-6">
                            <i class="fa fa-check-square fa-5x"></i>
                        </div>
                        <div class="col-xs-6 text-right">
                            <p class="announcement-heading">{{normal}}</p>
                            <p class="announcement-text">Valores normais na última hora!</p>
                        </div>
                    </div>
                </div>
                <a href="#">
                    <div class="panel-footer announcement-bottom">
                        <div class="row">
                            <div class="col-xs-6">
                                Ver
                            </div>
                            <div class="col-xs-6 text-right">
                                <i class="fa fa-arrow-circle-right"></i>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="panel panel-warning">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-6">
                            <i class="fa fa-warning fa-5x"></i>
                        </div>
                        <div class="col-xs-6 text-right">
                            <p class="announcement-heading">{{warning}}</p>
                            <p class="announcement-text">Valores de alerta na última hora!</p>
                        </div>
                    </div>
                </div>
                <a href="#">
                    <div class="panel-footer announcement-bottom">
                        <div class="row">
                            <div class="col-xs-6">
                                Ver
                            </div>
                            <div class="col-xs-6 text-right">
                                <i class="fa fa-arrow-circle-right"></i>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-6">
                            <i class="fa fa-times-circle fa-5x"></i>
                        </div>
                        <div class="col-xs-6 text-right">
                            <p class="announcement-heading">{{critical}}</p>
                            <p class="announcement-text">Valores críticos na última hora</p>
                        </div>
                    </div>
                </div>
                <a href="#">
                    <div class="panel-footer announcement-bottom">
                        <div class="row">
                            <div class="col-xs-6">
                                Ver
                            </div>
                            <div class="col-xs-6 text-right">
                                <i class="fa fa-arrow-circle-right"></i>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div><!-- /.row -->    

{% endblock %}

src/Ueb/UebOfThingsBundle/Resources/views/Default/login.html.twig
{% extends 'UebUebOfThingsBundle::layout.html.twig' %}

{% block javascripts %}
    {{parent()}}
{% endblock %}

{% block content -%}

    <h1>Login</h1>
    
    {{ wo_render_breadcrumbs() }}
    
    {% if error %}
        
        <div class="alert alert-dismissable alert-danger">
            <button type="button" class="close" data-dismiss="alert">×</button>
            {{ error.message }}
        </div>
    {% else %}
        <div class="alert alert-dismissable alert-info"> Insira os seus dados </div>
    {% endif %}
    
    <form action="{{ path('login_check') }}" method="post">
        <div class="form-group">
            <label for="inputEmail">Utilizador</label>
            <input type="text" class="form-control" id="username" name="_username" placeholder="Utilizador">
        </div>
        <div class="form-group">
            <label for="inputPassword">Palavra-Passe</label>
            <input type="password" class="form-control" id="password" name="_password" placeholder="Palavra-Passe">
        </div>
        <div class="checkbox">
            <label><input type="checkbox"> Lembrar-me</label>
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>

    
{% endblock %}

src/Ueb/UebOfThingsBundle/Resources/views/Default/nav.html.twig
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{{ path("homepage") }}">Ueb Of Things</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
            <li><a href="{{ path("homepage") }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-ticket"></i> Things / Feeds <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="{{ path("feeds") }}"><i class="fa fa-bars"></i> Todos</a></li>
                    <li><a href="{{ path("feedgroup") }}"><i class="fa fa-th-list"></i> Grupos</a></li>
                </ul>
            </li>
            <li><a href="{{ path("board") }}"><i class="fa fa-cogs"></i> Boards</a></li>
            <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-angle-double-down"></i> Advanced <b class="caret"></b></a>
            
                <ul class="dropdown-menu">
                    <li><a href="#"><i class="fa fa-code"></i> Code-Blocks</a></li>
                </ul>
            </li>
        </ul>

        <ul class="nav navbar-nav navbar-right navbar-user">
            {% if app.user %}
                {{ render( controller (
                    'UebUebOfThingsBundle:Navigation:userMenu'
                )) }}
            {% else %}
                <li><a href="{{ path("login") }}" ><i class="fa-sign-in"></i> Login </a></li>
            {% endif %}<!--
            <li class="dropdown alerts-dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> Alertas <span class="badge">3</span> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    
                    <li><a href="#">Default <span class="label label-default">Default</span></a></li>
                    
                    <li class="divider" id="divider_alerts"></li>
                    <li><a href="#">View All</a></li>
                </ul>
            </li>
            <li class="dropdown user-dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> John Smith <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="#"><i class="fa fa-user"></i> Profile</a></li>
                    <li><a href="#"><i class="fa fa-envelope"></i> Inbox <span class="badge">7</span></a></li>
                    <li><a href="#"><i class="fa fa-gear"></i> Settings</a></li>
                    <li class="divider"></li>
                    <li><a href="#"><i class="fa fa-power-off"></i> Log Out</a></li>
                </ul>
            </li>-->
        </ul>
    </div><!-- /.navbar-collapse -->
</nav>

src/Ueb/UebOfThingsBundle/Resources/views/Default/settings.html.twig
{% extends 'UebUebOfThingsBundle::layout.html.twig' %}

{% block javascripts %}
    {{parent()}}
{% endblock %}

{% block content -%}
    
<h1>Definições</h1>

{{ wo_render_breadcrumbs() }}

<div class="panel panel-info">
    <div class="panel-heading">
        <h4> Informação Pessoal </h4>
    </div>
    <div class="panel-body">
        {{ form(form) }}
    </div>
</div>

{{ form(form) }}

{% endblock %}

src/Ueb/UebOfThingsBundle/Resources/views/Default/userMenu.html.twig
<li class="dropdown alerts-dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> Alertas {{ badge(user.notifications|length) }} <b class="caret"></b></a>
    <ul class="dropdown-menu" id="user-notifications-dropdown">

        {% for notification in user.notifications %}
            <li><a href="{{ path("feed_show", {'id': notification.feeddata.feed.id }) }}">
                    {{notification.feeddata.feed.name}} 
                    {% if notification.typeToString == "warning" %}
                        <span class="label label-warning">
                        {% elseif notification.typeToString == "critical" %}
                            <span class="label label-danger">
                            {% endif %}
                            {{ notification.feeddata.value }} {{ notification.feeddata.feed.measureunit }}
                        </span>
                </a></li>
            {% endfor %}
        <!--<li><a href="#">Default <span class="label label-default">Default</span></a></li>-->

        <li class="divider" id="divider_alerts"></li>
        <li><a href="#" onClick="cleanAlerts('{{path("clean_notifications")}}');">Limpar Alertas</a></li>
    </ul>
</li>
<li class="dropdown user-dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> {{ user.username }} <b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li><a href="{{path("user_settings")}}"><i class="fa fa-gear"></i> Definições</a></li>
        <li class="divider"></li>
        <li><a href=" {{path("logout") }}"><i class="fa fa-power-off"></i> Log Out</a></li>
    </ul>
</li>