src/Ueb/UebOfThingsBundle/Entity/Feed.php
<?php

namespace Ueb\UebOfThingsBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\ExecutionContextInterface;

/**
 * Feed
 *
 * @ORM\Table(name="feed")
 * @ORM\Entity(repositoryClass="Ueb\UebOfThingsBundle\Repository\FeedRepository")
 */
class Feed {

    
    private static $s = 60;
    
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=100, nullable=false, unique=true)
     */
    private $name;
    

    /**
     * @var string
     *
     * @ORM\Column(name="mac", type="string", length=100, nullable=false, unique=true)
     */
    private $mac;

    /**
     * @var string
     *
     * @ORM\ManyToOne(targetEntity="Board", inversedBy="feeds")
     * @ORM\JoinColumn(name="board_id", referencedColumnName="id")
     */
    private $board;

    /**
     * @ORM\OneToMany(targetEntity="FeedData", mappedBy="feed", cascade={"persist", "remove"}))
     **/
    private $data;

    /**
     *
     * @var Thing 
     * 
     * @ORM\ManyToOne(targetEntity="Thing")
     * @ORM\JoinColumn(name="thing_id", referencedColumnName="id")
     * 
     */
    private $thing;

    /**
     * 
     * @var float
     * 
     * @ORM\Column(name="warning_value", nullable=true, type="float")
     * 
     */
    private $warningValue;

    /**
     * 
     * @var float
     * 
     * @ORM\Column(name="critical_value", type="float",nullable=true)
     * 
     */
    private $criticalVaue;

    /**
     * 
     * @var string
     * 
     * @ORM\Column(name="measureunit", type="string", nullable=true, length=25)
     * 
     */
    private $measureunit;
    
    /**
     * 
     * @ORM\ManyToOne(targetEntity="FeedGroup", inversedBy="feeds")
     * @ORM\JoinColumn(name="group_id", referencedColumnName="id")
     */
    private $group;


    public function __construct() {
        $this->data = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Feed
     */
    public function setName($name) {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName() {
        return $this->name;
    }

    /**
     * Set mac
     *
     * @param string $mac
     * @return Feed
     */
    public function setMac($mac) {
        $this->mac = $mac;

        return $this;
    }

    /**
     * Get mac
     *
     * @return string 
     */
    public function getMac() {
        return $this->mac;
    }

    /**
     * Set board
     *
     * @param \Ueb\UebOfThingsBundle\Entity\Board $board
     * @return Feed
     */
    public function setBoard(\Ueb\UebOfThingsBundle\Entity\Board $board = null) {
        $this->board = $board;

        return $this;
    }

    /**
     * Get board
     *
     * @return \Ueb\UebOfThingsBundle\Entity\Board 
     */
    public function getBoard() {
        return $this->board;
    }

    /**
     * Add data
     *
     * @param \Ueb\UebOfThingsBundle\Entity\FeedData $data
     * @return Feed
     */
    public function addDatum(\Ueb\UebOfThingsBundle\Entity\FeedData $data) {
        
        $data->setFeed($this);
        $this->data[] = $data;
        
        
        return $this;
    }

    /**
     * Remove data
     *
     * @param \Ueb\UebOfThingsBundle\Entity\FeedData $data
     */
    public function removeDatum(\Ueb\UebOfThingsBundle\Entity\FeedData $data) {
        
        $data->setFeed();
        $this->data->removeElement($data);
    }

    /**
     * Get data
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getData($period=null) {
        if(!$period) {
            return $this->data;
        }
        
        switch ($period) {
            case 'day':
  
                break;
            case 'week':

                break;
            case 'year':

                break;
            default:
                break;
        }
        
        return null;
    }

    /**
     * Set thing
     *
     * @param \Ueb\UebOfThingsBundle\Entity\Thing $thing
     * @return Feed
     */
    public function setThing(\Ueb\UebOfThingsBundle\Entity\Thing $thing = null) {
        $this->thing = $thing;

        return $this;
    }

    /**
     * Get thing
     *
     * @return \Ueb\UebOfThingsBundle\Entity\Thing 
     */
    public function getThing() {
        return $this->thing;
    }

    /**
     * Set warningValue
     *
     * @param float $warningValue
     * @return Feed
     */
    public function setWarningValue($warningValue) {
        $this->warningValue = $warningValue;

        return $this;
    }

    /**
     * Get warningValue
     *
     * @return float 
     */
    public function getWarningValue() {
        return $this->warningValue;
    }

    /**
     * Set criticalVaue
     *
     * @param float $criticalVaue
     * @return Feed
     */
    public function setCriticalVaue($criticalVaue) {
        $this->criticalVaue = $criticalVaue;

        return $this;
    }

    /**
     * Get criticalVaue
     *
     * @return float 
     */
    public function getCriticalVaue() {
        return $this->criticalVaue;
    }

    /**
     * Set measureunit
     *
     * @param string $measureunit
     * @return Feed
     */
    public function setMeasureunit($measureunit) {
        $this->measureunit = $measureunit;

        return $this;
    }

    /**
     * Get measureunit
     *
     * @return string 
     */
    public function getMeasureunit() {
        return $this->measureunit;
    }
    
    public function getTypeOfThing() {
        return $this->thing->getType();
    }
    
    /**
     * Set group
     *
     * @param \Ueb\UebOfThingsBundle\Entity\FeedGroup $group
     * @return Feed
     */
    public function setGroup(\Ueb\UebOfThingsBundle\Entity\FeedGroup $group = null)
    {
        $this->group = $group;

        return $this;
    }

    /**
     * Get group
     *
     * @return \Ueb\UebOfThingsBundle\Entity\FeedGroup 
     */
    public function getGroup()
    {
        return $this->group;
    }

    /**
     * Get last FeedData
     * 
     * @return FeedData
     */
    public function getCurrentData() {
        
        $last_value = $this->data->last();
        
        
        if($last_value) {
            
            $now = new \DateTime();
            
            $seconds = abs($now->getTimeStamp() - $last_value->getTime()->getTimeStamp());
            
            if($seconds > self::$s) {
                return null;
            }
            
            return $last_value;
        }
        return null;
    }    
    
    public function getCountNormalValues() {
        
        $count = 0 ;
        
        if (!$this->data->isEmpty()) {
            foreach ($this->data->toArray() as $data) {
                if($data->getValue() < $this->warningValue) {
                    $count++;
                }
            }
        }
        
        return $count;
        
    }
    
    public function getCountWarningValues() {
        
        $count = 0 ;
        
        if (!$this->data->isEmpty()) {
            foreach ($this->data->toArray() as $data) {
                if($data->getValue() >= $this->warningValue && $data->getValue()< $this->criticalVaue) {
                    $count++;
                }
            }
        }
        
        return $count;
        
    }
    
    public function getCountCriticalValues() {
        
        $count = 0 ;
        
        if (!$this->data->isEmpty()) {
            foreach ($this->data->toArray() as $data) {
                if($data->getValue() >= $this->criticalVaue) {
                    $count++;
                }
            }
        }
        
        return $count;
        
    }
    
    
    /**
     * 
     * @Assert\Callback
     */
    public function isBoardAbleToHaveThisFeed(ExecutionContextInterface $context) {

        if ($this->board) {
            if (!$this->board->canHaveFeeds()) {
                $context->addViolationAt("board", "Feed cannot be associated here!");
            }
        }
    }
    
    public function __toString() {
        return $this->name;
    }

    
}

src/Ueb/UebOfThingsBundle/Controller/FeedController.php
<?php

namespace Ueb\UebOfThingsBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Ueb\UebOfThingsBundle\Entity\Feed;
use Ueb\UebOfThingsBundle\Form\FeedType;

/**
 * Feed controller.
 *
 * @Route("/feed")
 */
class FeedController extends Controller {

    /**
     * Lists all Feed entities.
     *
     * @Route("/", name="feeds")
     * @Method("GET")
     * @Template()
     */
    public function indexAction() {
        $em = $this->getDoctrine()->getManager();

        $sensors = $em->getRepository('UebUebOfThingsBundle:Feed')->findAllSensors();
        $actuators = $em->getRepository('UebUebOfThingsBundle:Feed')->findAllActuators();

        $breadcrumbs = $this->get("white_october_breadcrumbs");
        $breadcrumbs->addItem("Dashboard", $this->get("router")->generate("homepage"));
        $breadcrumbs->addItem("Things / Feeds");

        return array(
            'sensors' => $sensors,
            'actuators' => $actuators
        );
    }

    /**
     * Creates a new Feed entity.
     *
     * @Route("/", name="feed_create")
     * @Method("POST")All();

        $breadcrumbs = $this->get("white_october_breadcrumbs");
        $breadcrumbs->addItem("Dashboard", $this->get("router")->generate("homepage"));
        $breadcrumbs->addItem("Things / Feeds");

        return array(
     * @Template("UebUebOfThingsBundle:Feed:new.html.twig")
     */
    public function createAction(Request $request) {
        $entity = new Feed();
        $form = $this->createCreateForm($entity);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('feed_show', array('id' => $entity->getId())));
        }

        return array(
            'entity' => $entity,
            'form' => $form->createView(),
        );
    }

    /**
     * Creates a form to create a Feed entity.
     *
     * @param Feed $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCreateForm(Feed $entity) {
        $form = $this->createForm(new FeedType(), $entity, array(
            'action' => $this->generateUrl('feed_create'),
            'method' => 'POST',
        ));

        return $form;
    }

    /**
     * Displays a form to create a new Feed entity.
     *
     * @Route("/new", name="feed_new")
     * @Method("GET")
     * @Template()
     */
    public function newAction() {
        $entity = new Feed();
        $form = $this->createCreateForm($entity);

        $breadcrumbs = $this->get("white_october_breadcrumbs");
        $breadcrumbs->addItem("Dashboard", $this->generateUrl('homepage'));
        $breadcrumbs->addItem("Things / Feeds", $this->generateUrl('feeds'));
        $breadcrumbs->addItem("Novo Feed");

        return array(
            'entity' => $entity,
            'form' => $form->createView(),
        );
    }

    /**
     * Finds and displays a Feed entity.
     *
     * @Route("/{id}", name="feed_show")
     * @Method("GET")
     * @Template()
     */
    public function showAction($id) {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('UebUebOfThingsBundle:Feed')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Feed entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        $breadcrumbs = $this->get("white_october_breadcrumbs");
        $breadcrumbs->addItem("Dashboard", $this->generateUrl('homepage'));
        $breadcrumbs->addItem("Things / Feeds", $this->generateUrl('feeds'));
        $breadcrumbs->addItem($entity->getName());
        
      

        return array(
            'entity' => $entity,
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Displays a form to edit an existing Feed entity.
     *
     * @Route("/{id}/edit", name="feed_edit")
     * @Method("GET")
     * @Template()
     */
    public function editAction($id) {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('UebUebOfThingsBundle:Feed')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Feed entity.');
        }

        $editForm = $this->createEditForm($entity);
        $deleteForm = $this->createDeleteForm($id);

        $breadcrumbs = $this->get("white_october_breadcrumbs");
        $breadcrumbs->addItem("Dashboard", $this->generateUrl('homepage'));
        $breadcrumbs->addItem("Things / Feeds", $this->generateUrl('feeds'));
        $breadcrumbs->addItem($entity->getName(), $this->generateUrl('feed_show', array('id' => $entity->getId())));
        $breadcrumbs->addItem("Editar");

        return array(
            'entity' => $entity,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Creates a form to edit a Feed entity.
     *
     * @param Feed $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createEditForm(Feed $entity) {
        $form = $this->createForm(new FeedType(), $entity, array(
            'action' => $this->generateUrl('feed_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));
        
        $form->remove('thing');

        return $form;
    }

    /**
     * Edits an existing Feed entity.
     *
     * @Route("/{id}", name="feed_update")
     * @Method("PUT")
     * @Template("UebUebOfThingsBundle:Feed:edit.html.twig")
     */
    public function updateAction(Request $request, $id) {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('UebUebOfThingsBundle:Feed')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Feed entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createEditForm($entity);
        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
            $em->flush();

            return $this->redirect($this->generateUrl('feed_edit', array('id' => $id)));
        }

        return array(
            'entity' => $entity,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Deletes a Feed entity.
     *
     * @Route("/{id}", name="feed_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, $id) {
        $form = $this->createDeleteForm($id);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('UebUebOfThingsBundle:Feed')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Feed entity.');
            }

            
            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('feeds'));
    }

    /**
     * Creates a form to delete a Feed entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id) {
        return $this->createFormBuilder()
                        ->setAction($this->generateUrl('feed_delete', array('id' => $id)))
                        ->setMethod('DELETE')
                        ->add('submit', 'submit', array('label' => 'Delete'))
                        ->getForm()
        ;
    }

    /**
     * Get all Feed Data
     * 
     * @Route(
     *  "/{id}/data/{period}.{_format}",
     *  defaults={"_format" = "json" },
     *  requirements = { "_format" = "html|json", "period" = "hour|day|week|month" },
     *  name="feed_data"
     * )
     * @Template()
     */
    public function feedsDataAction($id, $period) {
        $em = $this->getDoctrine()->getManager();
        $repository= $em->getRepository("UebUebOfThingsBundle:Feed");
        $feed = $repository->findFeedJoinedByFeedData($id, $period);

        if (!$feed) {
            $feed_temp = $repository->find($id);

            if (!$feed_temp) {
                throw $this->createNotFoundException('Unable to find Feed entity.');
            }
            
            $feed = new Feed();
            $feed->setMeasureunit($feed_temp->getMeasureUnit());
        }
        
        return array(
            'feed' => $feed,
            'period' => $period,
            'last_value' => $feed->getCurrentData()
        );
    }
    

}

src/Ueb/UebOfThingsBundle/Resources/views/Feed/edit.html.twig
{% extends 'UebUebOfThingsBundle::layout.html.twig' %}

{% block javascripts %}
    {{parent()}}
{% endblock %}

{% block content -%}
    <h1>Editar Feed</h1>
    {{ wo_render_breadcrumbs() }}
    
    {{ form(edit_form) }}
    

        
    <li>
        <a href="{{ path('feeds') }}">
            Back to the list
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>

{% endblock %}

src/Ueb/UebOfThingsBundle/Resources/views/Feed/feedsData.html.twig
{% extends 'UebUebOfThingsBundle::layout.html.twig' %}

{% block content %}

{% endblock %}

src/Ueb/UebOfThingsBundle/Resources/views/Feed/feedsData.json.twig
{
    "period": "{{period}}",
    "measureunit": "{{feed.measureunit}}",
    "data": [
    {% if feed.data is defined %}
    {% for data in feed.data %}
        {
            "time": "{{ data.time|date('Y-m-d H:i:s') }}",
            "value": "{{ data.value }}"
        }{% if loop.last == false %},{% endif %}
    {% endfor %}
    {% endif %}
    ],
    "last_value": {% if last_value is not null %} "{{ last_value.value }}" {% else %} "" {% endif %}
}

src/Ueb/UebOfThingsBundle/Resources/views/Feed/index.html.twig
{% extends 'UebUebOfThingsBundle::layout.html.twig' %}

{% block stylesheets %}
    {{ parent () }}
    {% stylesheets 'bundles/uebuebofthings/css/datatables.css' filter='cssrewrite' %}
    <link rel="stylesheet" href="{{ asset_url }}" />
    {% endstylesheets %}
{% endblock %}

{% block javascripts %}
    {{parent()}}
    {% javascripts 
    '@UebUebOfThingsBundle/Resources/public/js/datatables/jquery.dataTables.js' 
    '@UebUebOfThingsBundle/Resources/public/js/datatable.js' %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
{% endblock %}

{% block content -%}
    <h1>Feeds</h1>
    {{ wo_render_breadcrumbs() }}


    <div class="panel panel-info">
        <div class="panel-heading">
            <h4>Sensores</h4>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table id="datatable1" class="table table-striped table-bordered no-footer">
                    <thead>
                        <tr>
                            <th>Nome <i class="fa fa-sort"></i></th>
                            <th>Grupo <i class="fa fa-sort"></i></th>
                            <th>Valor Atual <i class="fa fa-sort"></i></th>
                            <th>Valor Alarme <i class="fa fa-sort"></i></th>
                            <th>Valor Crítico <i class="fa fa-sort"></i></th>
                            <th>Placa <i class="fa fa-sort"></i></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for entity in sensors %}
                            <tr>
                                <td><a href="{{ path('feed_show', { 'id': entity.id }) }}">{{ entity.name }}</a></td>
                                {% if entity.group %}
                                    <td>{{entity.group}}</td>
                                {% else %}
                                    <td>-</td>
                                {% endif %}
                                {% if entity.currentdata is null %}
                                    <td>-</td>
                                {% else %}
                                    <td>{{ entity.currentdata.value}} {{ entity.measureunit}}</td>
                                {% endif %}
                                <td>{{ entity.warningValue }} {{ entity.measureunit }}</td>
                                <td>{{ entity.criticalVaue }} {{ entity.measureunit }}</td>
                                {% if entity.board %}
                                    <td>{{ entity.board.name }}</td>
                                {% else %}
                                    <td>Sem placa associada</td>
                                {% endif %}
                                <td><a href="{{ path('feed_show', { 'id': entity.id }) }}"><i class="fa fa-chevron-circle-right"> Mais</i></a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
                    
    <div class="panel panel-info">
        <div class="panel-heading">
            <h4>Actuadores</h4>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table id="datatable2" class="table table-striped table-bordered no-footer">
                    <thead>
                        <tr>
                            <th>Nome <i class="fa fa-sort"></i></th>
                            <th>Grupo <i class="fa fa-sort"></i></th>
                            <th>Valor Atual <i class="fa fa-sort"></i></th>
                            <th>Placa <i class="fa fa-sort"></i></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for entity in actuators %}
                            <tr>
                                <td><a href="{{ path('feed_show', { 'id': entity.id }) }}">{{ entity.name }}</a></td>
                                {% if entity.group %}
                                    <td>{{entity.group}}</td>
                                {% else %}
                                    <td>-</td>
                                {% endif %}
                                {% if entity.currentdata is null %}
                                    <td>-</td>
                                {% else %}
                                    <td>{{ entity.currentdata.value}} {{ entity.measureunit}}</td>
                                {% endif %}
                                {% if entity.board %}
                                    <td>{{ entity.board.name }}</td>
                                {% else %}
                                    <td>Sem placa associada</td>
                                {% endif %}
                                <td><a href="{{ path('feed_show', { 'id': entity.id }) }}"><i class="fa fa-chevron-circle-right"> Mais</i></a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>                



    <div class="col-lg-1 text-center"> 
        <input type="button" value="Novo Feed" onClick="window.location.href = '{{ path('feed_new') }}'" class="btn btn-primary">   
    </div>
{% endblock %}

src/Ueb/UebOfThingsBundle/Resources/views/Feed/new.html.twig
{% extends 'UebUebOfThingsBundle::layout.html.twig' %}

{% block javascripts %}
    {{parent()}}
    {% javascripts '@UebUebOfThingsBundle/Resources/public/js/feedform.js'%}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
{% endblock %}

{% block content -%}
    <h1>Criar Feed</h1>
    {{ wo_render_breadcrumbs() }}

    
    {{ form_start(form) }}
        {{ form_row(form.name) }}
        {{ form_row(form.mac) }}
        {{ form_row(form.measureunit) }}
        {{ form_row(form.board) }}
        {{ form_row(form.thing) }}
        
    {{ form_end(form) }}

        <ul class="record_actions">
    <li>
        <a href="{{ path('feeds') }}">
            Back to the list
        </a>
    </li>
</ul>
{% endblock %}

src/Ueb/UebOfThingsBundle/Resources/views/Feed/show.html.twig
{% extends 'UebUebOfThingsBundle::layout.html.twig' %}

{% block javascripts %}
    {{parent()}}
    {% javascripts 
    '@UebUebOfThingsBundle/Resources/public/js/flot/jquery.flot.js'
    '@UebUebOfThingsBundle/Resources/public/js/flot/jquery.flot.resize.js'
    '@UebUebOfThingsBundle/Resources/public/js/flot/jquery.flot.tooltip.min.js'
    '@UebUebOfThingsBundle/Resources/public/js/flot/jquery.flot.time.js'
    '@UebUebOfThingsBundle/Resources/public/js/flot/jquery.flot.navigationControl.js'
    '@UebUebOfThingsBundle/Resources/public/js/feed.js' %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    
    {% endjavascripts %}
    <script type="text/javascript">
        var ajax_url = "{{path('feed_data', {'id': entity.id, 'format': 'json', 'period': 'hour'})}}";

        $(document).ready(function() {

            $("#select_period").change(function() {


                switch ($("select option:selected").val()) {
                    case 'h':
                        ajax_url = "{{path('feed_data', {'id': entity.id, 'format': 'json', 'period': 'hour'})}}";
                        GetData();
                        break;
                    case 'd':
                        ajax_url = "{{path('feed_data', {'id': entity.id, 'format': 'json', 'period': 'day'})}}";
                        GetData();
                        break;
                    case 'w':
                        ajax_url = "{{path('feed_data', {'id': entity.id, 'format': 'json', 'period': 'week'})}}";
                        GetData();
                        break;
                    case 'm':
                        ajax_url = "{{path('feed_data', {'id': entity.id, 'format': 'json', 'period': 'month'})}}";
                        GetData();
                        break;
                    default:
                        break;
                }

            });

        });

    </script>
{% endblock %}



{% block content -%}
   
    <h1>{{ entity.name }}</h1>
    {{ wo_render_breadcrumbs() }}

    <div class="panel panel-info">
        <div class="panel-heading">
            <h4>Visão Geral</h4>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-6">
                    <table class="record_properties">
                        <tbody>
                            <tr>
                                <th>Nome</th>
                                <td>{{ entity.name }}</td>
                            </tr>
                            <tr>
                                <th>Grupo</th>
                                <td>{{ entity.group }}</td>
                            </tr>
                            <tr>
                                <th>Mac</th>
                                <td>{{ entity.mac }}</td>
                            </tr>
                            {# Check if is Sensor (ThingType = 0 for sensor, 1 for actuator) #}
                            {% if entity.typeOfThing == 0 %}
                            <tr>
                                <th>Valor de Alarme</th>
                                <td>{{ entity.warningValue }}</td>  
                            </tr>
                            <tr>
                                <th>Valor Critico</th>
                                <td>{{ entity.criticalVaue }}</td>
                            </tr>
                            {% endif %}
                            <tr>
                                <th>Unidade de Medida   </th>
                                <td>{{ entity.measureunit }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="col-lg-6 text-right">
                    <h3>Valor Atual</h3>
                    <h4 id="last_value">
                        {% if entity.currentdata is null %}
                            -
                        {% else %}
                            {{ entity.currentdata.value}} {{ entity.measureunit}}
                        {% endif %}
                    </h4>
                </div>
            </div>
        </div>
    </div>

                            
    <div class="panel panel-info">
        <div class="panel-heading">
            <div class="row">
                <h3 class="col-lg-6 panel-title"><i class="fa fa-bar-chart-o"></i> {{ entity.name }} - Histórico Valores {{entity.measureunit}}</h3>
                <div class="col-lg-3 text-right" id="loading"> 
                    <button class="btn btn-default" onclick="GetData()" type="button">
                        Refresh
                        <i class="fa fa-refresh"></i>
                    </button>

                </div>
                <div class="col-lg-3 text-right">

                    <select id="select_period" class="form-control">
                        <option select="selected" value="h">Hora</option>
                        <option value="d">Dia</option>
                        <option value="w">Semana</option>
                        <option value="m">Mes</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div class="flot-chart">
                <div class="flot-chart-content" id="flot-chart-line" style="padding: 0px; position: relative;"></div>
            </div>
        </div>
    </div>
    


    <ul class="record_actions">
        <li>
            <a href="{{ path('feeds') }}">
                Back to the list
            </a>
        </li>
        <li>
            <a href="{{ path('feed_edit', { 'id': entity.id }) }}">
                Edit
            </a>
        </li>
        <li>{{ form(delete_form) }}</li>
    </ul>
{% endblock %}